### ISSUE TITLE
error

### ISSUE THREAD

**Issue by gpcr** [paulgribble/pubmed#1]
How to over come this?
```
searched: gribble pl[au]
Entity: line 1: parser error : Space required after the Public Identifier
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
                                                 ^
Entity: line 1: parser error : SystemLiteral " or ' expected
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
                                                 ^
Entity: line 1: parser error : SYSTEM or PUBLIC, the URI is missing
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
                                                 ^
Segmentation fault (core dumped)

```
Thanks

**Comment by paulgribble** [comment]
Thanks for this—I think something has changed with the HTML that PubMed returns from a query... and the libxml parser doesn't like it. I will look into it,

**Comment by paulgribble** [comment]
OK solved ... the base URLs need now to be https instead of http

things should work again

thanks for spotting this

**Comment by gpcr** [comment]
Thanks for quick response and solution

**Comment by gpcr** [comment]
./pubmed  'metpally' 10

Fri Apr 21 13:09:32 2017
searched: metpally
returned 10/21

Abul-Husn NS, Manickam K, Jones LK, Wright EA, Hartzel DN, Gonzaga-Jauregui C, O'Dushlaine C, Leader JB, Lester Kirchner H, Lindbuchler DM, Barr ML, Giovanni MA, Ritchie MD, Overton JD, Reid JG, Metpally RP, Wardeh AH, Borecki IB, Yancopoulos GD, Baras A, Shuldiner AR, Gottesman O, Ledbetter DH, Carey DJ, Dewey FE, Murray MF (2016) Genetic identification of familial hypercholesterolemia within a single U.S. health care system. Science 354(6319).
`Segmentation fault (core dumped)`
